In [2]:
import numpy as np

In [5]:
a = np.array([1,2,5,6])

In [6]:
a

array([1, 2, 5, 6])

In [7]:
b = np.array([2, "aaa", True])

In [8]:
b

array(['2', 'aaa', 'True'], dtype='<U21')

array(2)

In [9]:
b = np.array([2, True])

In [10]:
b

array([2, 1])

In [11]:
b= 111
b

111

In [12]:
b

111

In [13]:
a

array([1, 2, 5, 6])

In [14]:
a

array([1, 2, 5, 6])

In [15]:
b = a[1:3]

In [16]:
b

array([2, 5])

In [17]:
b[:] = 1111
b

array([1111, 1111])

In [18]:
a

array([   1, 1111, 1111,    6])